### ISSUE TITLE
zlib.error: Error -3 while decompressing data: unknown compression method

### ISSUE THREAD

**Issue by kumpisteszta** [matpow2/anaconda#18]
I get this error when I try to decompile a CCN.

Here's the full stack trace:
Could not import all platforms
(unknown chunk 8774)
(unknown chunk 8783)
(unknown chunk 8781)
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\User\Desktop\asd\anaconda-master\anaconda-master\Chowdren\chowdren\run.py", line 40, in <module>
    main()
  File "C:\Users\User\Desktop\asd\anaconda-master\anaconda-master\Chowdren\chowdren\run.py", line 37, in main
    Converter(args)
  File "chowdren\converter.py", line 634, in __init__
    game = GameData(ByteReader(fp))
  File "mmfparser\loader.pyx", line 20, in mmfparser.loader.DataLoader.__init__ (./mmfparser/loader.cpp:975)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1090)
  File "mmfparser\loader.pyx", line 49, in mmfparser.loader.DataLoader.read (./mmfparser/loader.cpp:1753)
  File "..\mmfparser\data\gamedata.py", line 102, in read
    chunks = self.new(ChunkList, reader)
  File "mmfparser\loader.pyx", line 37, in mmfparser.loader.DataLoader.new (./mmfparser/loader.cpp:1284)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1090)
  File "mmfparser\data\chunk.pyx", line 157, in mmfparser.data.chunk.ChunkList.read (./mmfparser/data/chunk.cpp:3408)
  File "mmfparser\loader.pyx", line 37, in mmfparser.loader.DataLoader.new (./mmfparser/loader.cpp:1284)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1090)
  File "mmfparser\data\chunk.pyx", line 77, in mmfparser.data.chunk.Chunk.read (./mmfparser/data/chunk.cpp:2218)
  File "mmfparser\loader.pyx", line 37, in mmfparser.loader.DataLoader.new (./mmfparser/loader.cpp:1284)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1090)
  File "mmfparser\data\chunkloaders\imagebank.pyx", line 585, in mmfparser.data.chunkloaders.imagebank.ImageBank.read (./mmfparser/data/chunkloaders/imagebank.cpp:11567)
  File "mmfparser\loader.pyx", line 37, in mmfparser.loader.DataLoader.new (./mmfparser/loader.cpp:1284)
  File "mmfparser\loader.pyx", line 31, in mmfparser.loader.DataLoader.init (./mmfparser/loader.cpp:1090)
  File "mmfparser\data\chunkloaders\imagebank.pyx", line 373, in mmfparser.data.chunkloaders.imagebank.ImageItem.read (./mmfparser/data/chunkloaders/imagebank.cpp:5096)
  File "..\mmfparser\data\zlibdata.py", line 27, in decompress
    return ByteReader(zlib.decompress(reader.read(compressedSize)))
zlib.error: Error -3 while decompressing data: unknown compression method

**Comment by matpow2** [comment]
Can you upload the CCN in question?

**Comment by kumpisteszta** [comment]
Here's it: http://www.mediafire.com/download/jmb5j7168d84znv/application.ccn
I hope mediafire is OK :) (or I can send it via email if it's not)

**Comment by kumpisteszta** [comment]
After some digging and stuff it turned out that there's something wrong with the ImageBank (it's not wrong because the game can run...). For example the first image (at 0x3EA88), it says that the decompressed size is 1048576 bytes, and the compressed is 16 bytes, but I that's impossible (or zlib knows somehing :) ). Maybe there's no data here instead these are some kind of pointers?
